application: drowblackjack
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css
- url: /images
  static_dir: images 
- url: /.*
  script: blackjack_controller.py
  login: required
